esphome:
  name: $name
  # friendly_name: $friendly_name # https://community.home-assistant.io/t/how-is-friendly-name-supposed-to-behave/542570/35
  area: $area

# Enable logging
logger:

# Enable Home Assistant API
api:
  # passwords are deprecated -- encryption keys are now preferred
  # password: ""
  encryption:
    key: !secret api_encryption_key

# Enable over-the-air updates.
ota:
  - platform: esphome
    password: !secret ota_passwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false           # Don't pick the first BSSID found

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_ap_password

# Captive portal for fallback authentication(?)
captive_portal:

# Enable Web server.
web_server:
  port: 80
  version: 3
  local: false                  # whether to include js files locally, or host them on the internet

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    entity_category: diagnostic
    disabled_by_default: true
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
      entity_category: diagnostic
      update_interval: 600s
    ssid:
      name: "${friendly_name} SSID"
      entity_category: diagnostic
      update_interval: 600s
    bssid:
      name: "${friendly_name} BSSID"
      entity_category: diagnostic
      disabled_by_default: true
      update_interval: 600s

# Exposed switches/buttons.
button:
  # Button to restart the device.
  - platform: restart
    name: "${friendly_name} Restart"

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 600s
    entity_category: diagnostic
    disabled_by_default: true

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 600s
    entity_category: diagnostic
    disabled_by_default: true
