substitutions:
  name: buzzer
  friendly_name: "Buzzer"
  area: Stairwell

esp8266:
  board: esp01_1m

packages:
  device_base: !include _common.yaml


# Global to store the enabled state of the buzzer
globals:
  - id: enabled
    type: bool
    restore_value: true
    initial_value: 'true'


switch:
  # Turn on/off the buzzer relay
  - platform: gpio
    id: relay
    inverted: false
    name: Door buzzer relay
    pin: GPIO0

  # It creates a "virtual" switch based on a global variable.
  - platform: template
    name: Buzzer enabled
    id: buzzer_enabled
    restore_mode: DISABLED
    turn_on_action:
      - globals.set:
          id: enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: enabled
          value: 'false'
    lambda: |-
      return id(enabled);

button:
  - platform: template
    name: Door buzzer
    id: buzzer_button
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(enabled);'
            then:
              - logger.log: "Button pressed"
              - switch.turn_on: relay
              - delay: 5s
              - switch.turn_off: relay
            else:
              - logger.log: "Button press ignored: buzzer disabled"
