# https://github.com/echavet/MitsubishiCN105ESPHome

# Compile with these filled in -- e.g.
# esphome -s name 'living_room_56' -s area 'Living room 56' -s friendly_name 'Living Room 56' run heat_pump.yaml
substitutions:
  name: replace_me
  friendly_name: "replace_me"
  area: replace_me

esp8266:
  board: esp01_1m

packages:
  device_base: !include _common.yaml

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome


# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "${friendly_name} heat pump"
    icon: mdi:heat-pump
    # visual:
    #   min_temperature: 60 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
    #   max_temperature: 85
    #   temperature_step:
    #     target_temperature: 0.5
    #     current_temperature: 0.1
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 60s    # update interval can be adjusted after a first run and logs monitoring
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: true
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true

# Default logging level
logger:
  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO
