substitutions:
  name: sauna
  friendly_name: "Sauna"
  area: Gym

<<: !include _common.yaml

sensor:
  # DHT11 temp/humidity sensor
  - platform: dht
    # model: DHT11
    pin: D2
      # number: D2
      # mode:
      #   input: true
      #   pullup: false           # This DHT11 has an external pullup resistor
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 60s
