substitutions:
  name: sauna
  friendly_name: "Sauna"
  area: Gym

esphome:
  name: $name
  friendly_name: $friendly_name
  area: $area

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

# Enable over-the-air updates.
ota:
  - platform: esphome
    password: !secret ota_passwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false           # Don't pick the first BSSID found

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_ap_password

# Captive portal for fallback authentication(?)
captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $friendly_name ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP
    ssid:
      name: $friendly_name SSID
    bssid:
      name: $friendly_name BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: $friendly_name Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: $friendly_name WiFi Signal
    update_interval: 60s

  # DHT11 temp/humidity sensor
  - platform: dht
    # model: DHT11
    pin: D2
      # number: D2
      # mode:
      #   input: true
      #   pullup: false           # This DHT11 has an external pullup resistor
    temperature:
      name: "Sauna temperature"
      accuracy_decimals: 1
    humidity:
      name: "Sauna humidity"
      accuracy_decimals: 1
    update_interval: 60s
