external_components:
  - source:
      type: local
      path: components

esphome:
  includes:
    - treadmill_controller.h

esp32:
  board: esp32dev
  variant: esp32
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"

packages:
  device_base: !include _common.yaml

logger:
  level: DEBUG

globals:
  - id: treadmill_speed
    type: float
    restore_value: no
    initial_value: '0.0'
  # Accumulator and count for hr average
  - id: hr_sum
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: hr_count
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: hr_average
    type: float
    restore_value: no
    initial_value: '0.0'

wifi:
  fast_connect: true

# Setup the UART for the MAX3232 connection
uart:
  id: treadmill_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400

treadmill_csafe_parser:
  id: csafe_parser
  uart_id: treadmill_bus

# For reading heart rate data
esp32_ble_tracker:
  on_ble_advertise:
    - then:
        lambda: |-
          if (x.get_name() == HEARTCAST || x.get_name() == ECHO) {
            // Check if we are already connected or connecting
            if (!id(heartcast_client).connected()) {
              ESP_LOGD("heartcast", "Found HeartCast at %s! Connecting...", x.address_str().c_str());

              // Use address_uint64() to get the numerical format the client needs
              id(heartcast_client).set_address(x.address_uint64());
              id(heartcast_client).connect();
            }
          }

# text_sensor:
#   # View BLE scanner results - spews lots of logs
#   - platform: ble_scanner
#     name: "BLE Devices Scanner"

ble_client:
  - mac_address: 00:00:00:00:00:00
    id: heartcast_client
    auto_connect: false  # We handle connection via the scanner
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_custom", "Connected! Attempting to enable notifications...");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_custom", "Disconnected from HeartCast.");

# TODO: display screen
#  - connecting status indicator
# TODO: CSAFE
#  - receive/parse
#  - encode/transmit

font:
  - file: 'SourceSansPro-Light.ttf'
    id: font1
    size: 22
  # - file: 'materialdesignicons-webfont.ttf'
  #   id: font2
  #   size: 16
  #   glyphs:
  #     - "\U000F1A0A" # "triangle-small-up"
  - file: 'materialdesignicons-webfont.ttf'
    id: font4
    size: 34
    glyphs:
      - "\U000F02D1" # "heart"
      - "\U000F02D5" # "heart-outline"
      - "\U000F046E" # "run-fast"
      - "\U000F070E" # "run"


i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false

display:
  - id: main_display
    platform: ssd1306_i2c
    model: "SSD1306 128x64"
    rotation: 180
    # reset_pin: D0
    address: 0x3C
    show_test_card: false
    lambda: |-
      float speed = id(treadmill_pid).get_output_speed();
      auto run_glyph = speed >= 5.0 ? "\U000F046E" : "\U000F070E";
      // Heart glyph
      it.printf(0, 26, id(font4), TextAlign::BASELINE_LEFT, "\U000F02D1");
      // Heart rate
      it.printf(40, 0, id(font1), "%.0f", id(hr_average));
      // Run glyph
      it.printf(0, it.get_height(), id(font4), TextAlign::BASELINE_LEFT, run_glyph);
      // Print current speed
      it.printf(40, it.get_height() - 26, id(font1), "%.1f", speed);


number:
  - platform: template
    name: "Target heart rate"
    id: target_hr
    unit_of_measurement: "BPM"
    icon: 'mdi:heart-pulse'
    min_value: 60
    max_value: 170
    restore_value: true
    optimistic: true
    step: 1

pid_controller:
  - id: treadmill_pid
    kp: 0.05
    ki: 0.001
    kd: 0.02
    output_min: 3.0
    output_max: 12.0

sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: heartcast_client
    name: "Apple Watch Heart Rate"
    id: hr_sensor
    service_uuid: '180d'        # Per BLE spec
    characteristic_uuid: '2a37' # Per BLE spec
    # descriptor_uuid: '2902'
    icon: 'mdi:heart-pulse'
    unit_of_measurement: "BPM"
    accuracy_decimals: 0
    notify: true  # This allows the iPhone to push updates to the ESP32
    update_interval: never # Don't poll -- wait for notifications
    lambda: |-
        // The first byte (x[0]) contains flags.
        // If bit 0 is 0, heart rate is in x[1] (uint8).
        // If bit 0 is 1, heart rate is in x[1] and x[2] (uint16).
        // ESP_LOGI("treadmill_controller", "x[0]: %x  x[1]: %x  x[2]: %x", x[0], x[1], x[2]);
        if (x.size() >= 2) {
          return (x[0] & 0x01) ? (float)((x[2] << 8) | x[1]) : (float)x[1];
        }
        return NAN;
    on_value:
      - lambda: |
          if (!isnan(x)) {
            id(hr_sum) += x;
            id(hr_count) += 1;
          }


# Poll treadmill speed every 5 seconds to stay in sync
interval:
  # Get the treadmill's reported speed
  - interval: 5s
    then:
      - lambda: |-
          id(csafe_parser).get_speed();
      - delay: 1s  # Wait for response
      - lambda: |-
          float polled_speed = id(csafe_parser).get_last_speed();
          id(treadmill_speed) = polled_speed;
          // ESP_LOGD("csafe", "Polled speed: %.2f mph", polled_speed);

  # PID update
  - interval: 15s
    then:
      - lambda: |-
          if (id(hr_count) > 0) {
            id(hr_average) = id(hr_sum) / id(hr_count);
            ESP_LOGI("pid", "HR average over last 15s: %.0f BPM from %d samples",
                     id(hr_average), (int)id(hr_count));

            float target = id(target_hr).state;

            // Use PID controller to calculate target speed
            // Error = Target HR - Current HR (positive means we need to increase speed)
            ESP_LOGD("pid", "Updating PID controller");
            float speed = id(treadmill_pid).update(target, id(hr_average), millis());

            ESP_LOGD("pid", "Setting speed to %.1f mph", speed);
            id(set_treadmill_speed).execute(speed);

            // Reset accumulator
            id(hr_sum) = 0.0;
            id(hr_count) = 0.0;
          } else {
            ESP_LOGI("pid", "No HR samples received in last N seconds");
            return;
          }

script:
  - id: set_treadmill_speed
    parameters:
      speed: float
    then:
      - lambda: |-
          // Send CSAFE command to set the speed
          id(csafe_parser).set_speed(speed);
